name: Test checkov

on:
  workflow_dispatch:

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          framework: terraform
          output_format: cli
          quiet: true
          soft_fail: false
